# Generated by Django 6.1 on 2026-08-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
