# Generated by Django 6.1 on 2026-08-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_achievement_certificate_education_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={},
        ),
        migrations.RemoveField(
            model_name='technology',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
