# Generated by Django 6.1 on 2026-08-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_technology_options_remove_technology_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='years_of_experience',
        ),
    ]
